import { type NextPage } from "next";
import Head from "next/head";
import Button from "@mui/joy/Button";

import { api } from "~/utils/api";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import { Box, Input, Typography } from "@mui/joy";

const Home: NextPage = () => {
  const todos = api.todo.getTodos.useQuery();
  const session = useSession();
  const router = useRouter();

  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Box
          sx={{
            maxWidth: 720,
            px: "20px",
            mx: "auto",
          }}
        >
          <Typography
            level="display2"
            sx={{
              mt: 2,
              mb: 4,
            }}
            color="primary"
          >
            坚果待办
          </Typography>
          <Input size="lg" placeholder="待办项" />
        </Box>
      </main>
    </>
  );
};

export default Home;
